# Generated by Django 6.0.1 on 2026-01-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsession',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
