# Generated by Django 6.0.1 on 2026-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_vpnsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsession',
            name='bytes_in',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='bytes_out',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='proposal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='uptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
